# Generated by Django 5.0.2 on 2024-03-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginactivity',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='machine_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='position',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
