# Generated by Django 5.0.2 on 2024-03-28 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('value', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('value', models.CharField(max_length=256, unique=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_materials', to='pages.materials')),
            ],
        ),
    ]
