# Generated by Django 5.0.2 on 2024-03-28 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_materials_submaterials'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=9, verbose_name='Longitude')),
                ('notes', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='pages.materials')),
                ('sub_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='pages.submaterials')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrderPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='', upload_to='delivery_orders/images/')),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='pages.deliveryorder')),
            ],
        ),
    ]
