# Generated by Django 5.0.2 on 2024-04-01 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_resetpasswordotp'),
        ('pages', '0004_deliveryorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('c', 'Created'), ('s', 'Started'), ('a', 'Accepted'), ('r', 'Rejected'), ('d', 'Done')], default='c', max_length=1),
        ),
        migrations.CreateModel(
            name='CompanyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('holding_time', models.DateTimeField(blank=True, null=True)),
                ('Problem', models.CharField(blank=True, choices=[('l', 'Location Problem'), ('m', 'Material Problem'), ('o', 'Other Problem')], max_length=1, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.company')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.deliveryorder')),
            ],
        ),
    ]
