# Generated by Django 5.0.2 on 2024-04-01 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_deliveryorder_status_companyorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companyorder', to='pages.deliveryorder'),
        ),
    ]
