# Generated by Django 5.0.2 on 2024-04-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_companyorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyorder',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
