from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup_page, name='signup_page'),
    path('signup_company/', views.signup_company, name='signup_company'),
    path('signin/', views.signin_page, name='signin_page'),
    path('signup_details/', views.signup_details_page, name='signup_details'),
    path('profile/', views.profile_page, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('confirm_mail/', views.confirm_mail, name='confirm_mail'),
    path('change_password/', views.change_password, name='change_password'),
    path('home/', views.home, name='home'),
    path('call_delivery/', views.call_delivery_page,
         name='call_delivery_page'),
    path('select_company/<int:delivery_order_id>/', views.select_company_page,
         name='select_company_page'),
    path('company_order/<int:company_order_id>/', views.manage_orders,
         name='company_order'),
    path('api/userprofile/', views.GetProfileData.as_view(),
         name='userprofile_retrieve'),
    path('api/update_userprofile/',
         views.update_user_data, name='update_user_data'),
    path('api/logout_all/',
         views.logout_all, name='logout_all'),
    path('api/desactivate_account/',
         views.desactivate_account, name='desactivate_account'),
    path('api/delete_account/',
         views.delete_account, name='delete_account'),
    path('api/update_password/',
         views.update_password, name='update_password'),
    path('api/send_otp/',
         views.send_otp, name='send_otp'),
    path('api/verify_otp/',
         views.verify_otp, name='verify_otp'),
    path('share_post/', views.share_post, name='share_post'),
    path('api/get_posts/', views.GetPosts.as_view(), name='get_posts'),
    path('api/toggle_like/<int:post_id>/',
         views.toggle_like, name='toggle_like'),
    path('api/send_comment/<int:post_id>/',
         views.send_comment, name='send_comment'),
    path('api/repost/<int:post_id>/',
         views.repost, name='repost'),
    path('api/get_materials/',
         views.GetMaterials.as_view(), name='get_materials'),
    path('api/create_delivery_order/',
         views.CreateDeliveryOrder.as_view(), name='create_delivery_order'),
    path('api/get_all_companies/',
         views.GetCompaniesListView.as_view(), name='get_all_companies'),
    path('api/call_company/', views.CallCompany.as_view(), name='call_company'),
    path('api/get_services/', views.GetServices.as_view(), name='get_services'),
    path('api/get_company_order/<int:pk>/', views.GetCompanyOrder.as_view(),
         name='get_company_order'),
    path('api/accept_refuse_order/', views.AcceptRefuseOrder.as_view(),
         name='accept_refuse_order'),
    path('api/get_history/', views.getUserHistory.as_view(), name='get_history'),
]
