# Generated by Django 5.0.2 on 2024-03-02 16:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.materialtype')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_services', to=settings.AUTH_USER_MODEL)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('note', models.TextField(blank=True, null=True)),
                ('material_subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.materialsubtype')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.materialtype')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='TempServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('note', models.TextField(blank=True, null=True)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_temp_services', to=settings.AUTH_USER_MODEL)),
                ('material_subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.materialsubtype')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.materialtype')),
            ],
        ),
    ]
